=== neaps/tide-database/schemas/station.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://neaps.js.org/station.schema.json",
  "title": "Tide Station",
  "type": "object",
  "required": [
    "id",
    "name",
    "continent",
    "country",
    "type",
    "latitude",
    "longitude",
    "timezone",
    "source",
    "license"
  ],
  "additionalProperties": false,
  "$defs": {
    "offsets": {
      "type": "object",
      "description": "Offsets for subordinate stations relative to a reference station",
      "required": [
        "reference",
        "height",
        "time"
      ],
      "additionalProperties": false,
      "properties": {
        "reference": {
          "type": "string",
          "description": "The ID of the reference station"
        },
        "height": {
          "type": "object",
          "description": "Defines the values to add or multiply with water levels (depending on type)",
          "required": [
            "high",
            "low",
            "type"
          ],
          "additionalProperties": false,
          "properties": {
            "high": {
              "type": "number",
              "description": "Height offset/multiplier for high tide - if type is 'ratio', this is a multiplier; if 'fixed', this is an offset to add (can be negative)"
            },
            "low": {
              "type": "number",
              "description": "Height offset/multiplier for low tide - if type is 'ratio', this is a multiplier; if 'fixed', this is an offset to add (can be negative)"
            },
            "type": {
              "enum": [
                "ratio",
                "fixed"
              ]
            }
          }
        },
        "time": {
          "type": "object",
          "description": "Defines the time to add to when a high or low tide will occur",
          "required": [
            "high",
            "low"
          ],
          "additionalProperties": false,
          "properties": {
            "high": {
              "type": "number",
              "description": "Time offset, in minutes, to add to the high tide (can be negative)"
            },
            "low": {
              "type": "number",
              "description": "Time offset, in minutes, to add to the low tide (can be negative)"
            }
          }
        }
      }
    }
  },
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique station ID for this database only, in the format of `country-region-station-name`.",
      "examples": [
        "us-ma-boston",
        "ar-u-puerto-madryn"
      ],
      "minLength": 4
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "continent": {
      "type": "string",
      "description": "Continent name in title case (e.g., `North America`, `Asia`, `Europe`)",
      "minLength": 1
    },
    "country": {
      "type": "string",
      "description": "Full country name (e.g., `United States`)",
      "minLength": 1
    },
    "region": {
      "type": "string",
      "description": "ISO 3166-2 region code, if available. If not, whatever local postal codes"
    },
    "timezone": {
      "type": "string",
      "description": "IANA time zone code (e.g. `America/Los_Angeles`)"
    },
    "disclaimers": {
      "type": "string",
      "description": "Any disclaimers about using this data"
    },
    "type": {
      "type": "string",
      "enum": [
        "reference",
        "subordinate"
      ]
    },
    "latitude": {
      "type": "number",
      "description": "Latitude, in decimal degrees"
    },
    "longitude": {
      "type": "number",
      "description": "Longitude, in decimal degrees"
    },
    "source": {
      "type": "object",
      "description": "",
      "required": [
        "name",
        "id",
        "published_harmonics",
        "url",
        "source_url"
      ],
      "additionalProperties": true,
      "properties": {
        "name": {
          "type": "string",
          "name": "Name of the source, i.e. `NOAA`"
        },
        "id": {
          "type": [
            "string",
            "number"
          ],
          "description": "The identifier used by the source for this station."
        },
        "published_harmonics": {
          "type": "boolean",
          "description": "Are the harmonics from published harmonic data? False means harmonics were computed."
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "URL to this station's data or information in the source's website"
        },
        "source_url": {
          "type": "string",
          "format": "uri",
          "description": "URL to the source API endpoint for this station's data"
        }
      }
    },
    "license": {
      "type": "object",
      "description": "Defines the license and whatever restrictions are placed on use of the data.",
      "required": [
        "type",
        "commercial_use",
        "url"
      ],
      "additionalProperties": true,
      "properties": {
        "type": {
          "type": "string",
          "description": "A short description of the type of license (i.e. MIT, public domain, etc)"
        },
        "commercial_use": {
          "type": "boolean",
          "description": "If `true` then there are no restrictions on commercial use."
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "A URL to the license information"
        },
        "notes": {
          "type": "string",
          "description": "Any additional restrictions or information on the license."
        }
      }
    },
    "harmonic_constituents": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "amplitude",
          "phase_UTC",
          "phase_local"
        ],
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string",
            "description": "Harmonic Constituent code (i.e. M2) - should be upper-case"
          },
          "description": {
            "type": [
              "string",
              "number",
              "null"
            ],
            "description": "Human-friendly description of the constituent"
          },
          "amplitude": {
            "type": "number",
            "description": "Amplitude"
          },
          "phase_UTC": {
            "type": "number",
            "description": "Phase in UTC"
          },
          "phase_local": {
            "type": "number",
            "description": "Phase for local timezone"
          },
          "speed": {
            "type": "number",
            "description": "Angular speed"
          },
          "comments": {
            "type": "string"
          }
        }
      }
    },
    "offsets": {
      "anyOf": [
        {
          "type": "object",
          "maxProperties": 0
        },
        {
          "$ref": "#/$defs/offsets"
        }
      ]
    },
    "datums": {
      "type": "object",
      "patternProperties": {
        "^[A-Z0-9_]+$": {
          "type": "number"
        }
      },
      "additionalProperties": false
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "type": {
            "const": "subordinate"
          }
        }
      },
      "then": {
        "properties": {
          "harmonic_constituents": {
            "maxItems": 0
          },
          "offsets": {
            "$ref": "#/$defs/offsets"
          }
        }
      }
    }
  ]
}

=== neaps/tide-database/data/us/fl/whiskey-creek-south-entrance-icww.json
{
  "id": "us-fl-whiskey-creek-south-entrance-icww",
  "name": "Whiskey Creek, south entrance, ICWW",
  "continent": "North America",
  "country": "United States",
  "region": "FL",
  "type": "subordinate",
  "latitude": 26.055,
  "longitude": -80.1133,
  "timezone": "America/New_York",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "8722971",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=8722971",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/8722971.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-fl-government-cut-miami-harbor-entrance",
    "height": {
      "type": "ratio",
      "high": 0.96,
      "low": 1.14
    },
    "time": {
      "high": 4,
      "low": 31
    }
  }
}

=== neaps/tide-database/data/us/mangareva-island.json
{
  "id": "us-mangareva-island",
  "name": "Mangareva Island",
  "continent": "North America",
  "country": "United States",
  "region": "",
  "type": "subordinate",
  "latitude": -23.13333333333333,
  "longitude": -134.9666666666667,
  "timezone": "Pacific/Gambier",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "TPT2835",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=TPT2835",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/TPT2835.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-pago-pago-harbor-tutuila-island",
    "height": {
      "type": "ratio",
      "high": 0.86,
      "low": 0.86
    },
    "time": {
      "high": -290,
      "low": -287
    }
  }
}

=== neaps/tide-database/data/us/ca/eureka-slough-bridge.json
{
  "id": "us-ca-eureka-slough-bridge",
  "name": "Eureka Slough Bridge",
  "continent": "North America",
  "country": "United States",
  "region": "CA",
  "type": "subordinate",
  "latitude": 40.8067,
  "longitude": -124.142,
  "timezone": "America/Los_Angeles",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "9418802",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=9418802",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/9418802.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-ca-humboldt-bay-north-spit",
    "height": {
      "type": "ratio",
      "high": 1.08,
      "low": 1.02
    },
    "time": {
      "high": 33,
      "low": 19
    }
  }
}

=== neaps/tide-database/data/us/ak/applegate-island.json
{
  "id": "us-ak-applegate-island",
  "name": "Applegate Island",
  "continent": "North America",
  "country": "United States",
  "region": "AK",
  "type": "subordinate",
  "latitude": 60.6233,
  "longitude": -148.165,
  "timezone": "America/Anchorage",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "9454794",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=9454794",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/9454794.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-ak-cordova",
    "height": {
      "type": "fixed",
      "high": -0.18,
      "low": 0
    },
    "time": {
      "high": -1,
      "low": 6
    }
  }
}

=== neaps/tide-database/data/us/la/barataria-pass.json
{
  "id": "us-la-barataria-pass",
  "name": "Barataria Pass",
  "continent": "North America",
  "country": "United States",
  "region": "LA",
  "type": "subordinate",
  "latitude": 29.275,
  "longitude": -89.945,
  "timezone": "America/Chicago",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "8761687",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=8761687",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/8761687.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-la-east-point-grand-isle",
    "height": {
      "type": "ratio",
      "high": 1.13,
      "low": 1.13
    },
    "time": {
      "high": 60,
      "low": -10
    }
  }
}

=== neaps/tide-database/data/us/sc/skull-creek-south-entrance-hilton-head-island.json
{
  "id": "us-sc-skull-creek-south-entrance-hilton-head-island",
  "name": "Skull Creek, south entrance, Hilton Head Island",
  "continent": "North America",
  "country": "United States",
  "region": "SC",
  "type": "subordinate",
  "latitude": 32.2233,
  "longitude": -80.7717,
  "timezone": "America/New_York",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "8669133",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=8669133",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/8669133.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-ga-fort-pulaski-savannah-river-entrance",
    "height": {
      "type": "ratio",
      "high": 1.05,
      "low": 1.05
    },
    "time": {
      "high": 34,
      "low": 23
    }
  }
}

=== neaps/tide-database/data/us/fishermans-rest.json
{
  "id": "us-fishermans-rest",
  "name": "Fishermans Rest",
  "continent": "North America",
  "country": "United States",
  "region": "",
  "type": "subordinate",
  "latitude": 29.733333333332993,
  "longitude": -83.53333333333299,
  "timezone": "America/New_York",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "TEC4305",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=TEC4305",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/TEC4305.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-fl-st-marks-river-entrance",
    "height": {
      "type": "ratio",
      "high": 0.93,
      "low": 0.86
    },
    "time": {
      "high": -14,
      "low": -2
    }
  }
}

=== neaps/tide-database/data/us/fl/suwannee-salt-creek.json
{
  "id": "us-fl-suwannee-salt-creek",
  "name": "Suwannee, Salt Creek",
  "continent": "North America",
  "country": "United States",
  "region": "FL",
  "type": "subordinate",
  "latitude": 29.3283,
  "longitude": -83.1517,
  "timezone": "America/New_York",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "8727577",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=8727577",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/8727577.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-fl-cedar-key",
    "height": {
      "type": "ratio",
      "high": 0.91,
      "low": 0.83
    },
    "time": {
      "high": -7,
      "low": 24
    }
  }
}
