=== neaps/tide-database/schemas/station.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://neaps.js.org/station.schema.json",
  "title": "Tide Station",
  "type": "object",
  "required": [
    "id",
    "name",
    "continent",
    "country",
    "type",
    "latitude",
    "longitude",
    "timezone",
    "source",
    "license"
  ],
  "additionalProperties": false,
  "$defs": {
    "offsets": {
      "type": "object",
      "description": "Offsets for subordinate stations relative to a reference station",
      "required": [
        "reference",
        "height",
        "time"
      ],
      "additionalProperties": false,
      "properties": {
        "reference": {
          "type": "string",
          "description": "The ID of the reference station"
        },
        "height": {
          "type": "object",
          "description": "Defines the values to add or multiply with water levels (depending on type)",
          "required": [
            "high",
            "low",
            "type"
          ],
          "additionalProperties": false,
          "properties": {
            "high": {
              "type": "number",
              "description": "Height offset/multiplier for high tide - if type is 'ratio', this is a multiplier; if 'fixed', this is an offset to add (can be negative)"
            },
            "low": {
              "type": "number",
              "description": "Height offset/multiplier for low tide - if type is 'ratio', this is a multiplier; if 'fixed', this is an offset to add (can be negative)"
            },
            "type": {
              "enum": [
                "ratio",
                "fixed"
              ]
            }
          }
        },
        "time": {
          "type": "object",
          "description": "Defines the time to add to when a high or low tide will occur",
          "required": [
            "high",
            "low"
          ],
          "additionalProperties": false,
          "properties": {
            "high": {
              "type": "number",
              "description": "Time offset, in minutes, to add to the high tide (can be negative)"
            },
            "low": {
              "type": "number",
              "description": "Time offset, in minutes, to add to the low tide (can be negative)"
            }
          }
        }
      }
    }
  },
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique station ID for this database only, in the format of `country-region-station-name`.",
      "examples": [
        "us-ma-boston",
        "ar-u-puerto-madryn"
      ],
      "minLength": 4
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "continent": {
      "type": "string",
      "description": "Continent name in title case (e.g., `North America`, `Asia`, `Europe`)",
      "minLength": 1
    },
    "country": {
      "type": "string",
      "description": "Full country name (e.g., `United States`)",
      "minLength": 1
    },
    "region": {
      "type": "string",
      "description": "ISO 3166-2 region code, if available. If not, whatever local postal codes"
    },
    "timezone": {
      "type": "string",
      "description": "IANA time zone code (e.g. `America/Los_Angeles`)"
    },
    "disclaimers": {
      "type": "string",
      "description": "Any disclaimers about using this data"
    },
    "type": {
      "type": "string",
      "enum": [
        "reference",
        "subordinate"
      ]
    },
    "latitude": {
      "type": "number",
      "description": "Latitude, in decimal degrees"
    },
    "longitude": {
      "type": "number",
      "description": "Longitude, in decimal degrees"
    },
    "source": {
      "type": "object",
      "description": "",
      "required": [
        "name",
        "id",
        "published_harmonics",
        "url",
        "source_url"
      ],
      "additionalProperties": true,
      "properties": {
        "name": {
          "type": "string",
          "name": "Name of the source, i.e. `NOAA`"
        },
        "id": {
          "type": [
            "string",
            "number"
          ],
          "description": "The identifier used by the source for this station."
        },
        "published_harmonics": {
          "type": "boolean",
          "description": "Are the harmonics from published harmonic data? False means harmonics were computed."
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "URL to this station's data or information in the source's website"
        },
        "source_url": {
          "type": "string",
          "format": "uri",
          "description": "URL to the source API endpoint for this station's data"
        }
      }
    },
    "license": {
      "type": "object",
      "description": "Defines the license and whatever restrictions are placed on use of the data.",
      "required": [
        "type",
        "commercial_use",
        "url"
      ],
      "additionalProperties": true,
      "properties": {
        "type": {
          "type": "string",
          "description": "A short description of the type of license (i.e. MIT, public domain, etc)"
        },
        "commercial_use": {
          "type": "boolean",
          "description": "If `true` then there are no restrictions on commercial use."
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "A URL to the license information"
        },
        "notes": {
          "type": "string",
          "description": "Any additional restrictions or information on the license."
        }
      }
    },
    "harmonic_constituents": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "amplitude",
          "phase_UTC",
          "phase_local"
        ],
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string",
            "description": "Harmonic Constituent code (i.e. M2) - should be upper-case"
          },
          "description": {
            "type": [
              "string",
              "number",
              "null"
            ],
            "description": "Human-friendly description of the constituent"
          },
          "amplitude": {
            "type": "number",
            "description": "Amplitude"
          },
          "phase_UTC": {
            "type": "number",
            "description": "Phase in UTC"
          },
          "phase_local": {
            "type": "number",
            "description": "Phase for local timezone"
          },
          "speed": {
            "type": "number",
            "description": "Angular speed"
          },
          "comments": {
            "type": "string"
          }
        }
      }
    },
    "offsets": {
      "anyOf": [
        {
          "type": "object",
          "maxProperties": 0
        },
        {
          "$ref": "#/$defs/offsets"
        }
      ]
    },
    "datums": {
      "type": "object",
      "patternProperties": {
        "^[A-Z0-9_]+$": {
          "type": "number"
        }
      },
      "additionalProperties": false
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "type": {
            "const": "subordinate"
          }
        }
      },
      "then": {
        "properties": {
          "harmonic_constituents": {
            "maxItems": 0
          },
          "offsets": {
            "$ref": "#/$defs/offsets"
          }
        }
      }
    }
  ]
}

=== neaps/tide-database/data/us/ma/cotuit-highlands.json
{
  "id": "us-ma-cotuit-highlands",
  "name": "Cotuit Highlands",
  "continent": "North America",
  "country": "United States",
  "region": "MA",
  "type": "subordinate",
  "latitude": 41.6083,
  "longitude": -70.4367,
  "timezone": "America/New_York",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "8447675",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=8447675",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/8447675.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-ma-boston",
    "height": {
      "type": "ratio",
      "high": 0.26,
      "low": 0.26
    },
    "time": {
      "high": 77,
      "low": 47
    }
  }
}

=== neaps/tide-database/data/us/shell-point-harkers-island.json
{
  "id": "us-shell-point-harkers-island",
  "name": "Shell Point, Harkers Island",
  "continent": "North America",
  "country": "United States",
  "region": "",
  "type": "subordinate",
  "latitude": 34.68333333333299,
  "longitude": -76.53333333333299,
  "timezone": "America/New_York",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "TEC2801",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=TEC2801",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/TEC2801.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-nc-cape-hatteras-fishing-pier",
    "height": {
      "type": "ratio",
      "high": 0.54,
      "low": 0.83
    },
    "time": {
      "high": 112,
      "low": 154
    }
  }
}

=== neaps/tide-database/data/us/ak/auke-bay.json
{
  "id": "us-ak-auke-bay",
  "name": "Auke Bay",
  "continent": "North America",
  "country": "United States",
  "region": "AK",
  "type": "subordinate",
  "latitude": 58.3817,
  "longitude": -134.645,
  "timezone": "America/Juneau",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "9452263",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=9452263",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/9452263.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-ak-juneau",
    "height": {
      "type": "fixed",
      "high": -0.12,
      "low": 0
    },
    "time": {
      "high": -6,
      "low": -3
    }
  }
}

=== neaps/tide-database/data/us/me/cape-porpoise.json
{
  "id": "us-me-cape-porpoise",
  "name": "Cape Porpoise",
  "continent": "North America",
  "country": "United States",
  "region": "ME",
  "type": "subordinate",
  "latitude": 43.3667,
  "longitude": -70.4317,
  "timezone": "America/New_York",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "8418772",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=8418772",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/8418772.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-me-portland",
    "height": {
      "type": "ratio",
      "high": 0.95,
      "low": 0.95
    },
    "time": {
      "high": 12,
      "low": 14
    }
  }
}

=== neaps/tide-database/data/us/wa/ship-harbor-fidalgo-island.json
{
  "id": "us-wa-ship-harbor-fidalgo-island",
  "name": "Ship Harbor, Fidalgo Island",
  "continent": "North America",
  "country": "United States",
  "region": "WA",
  "type": "subordinate",
  "latitude": 48.5067,
  "longitude": -122.677,
  "timezone": "America/Los_Angeles",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "9448772",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=9448772",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/9448772.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-wa-port-townsend",
    "height": {
      "type": "ratio",
      "high": 0.93,
      "low": 1.02
    },
    "time": {
      "high": 18,
      "low": 29
    }
  }
}

=== neaps/tide-database/data/us/fl/summerland-key-niles-channel-south.json
{
  "id": "us-fl-summerland-key-niles-channel-south",
  "name": "Summerland Key, Niles Channel South",
  "continent": "North America",
  "country": "United States",
  "region": "FL",
  "type": "subordinate",
  "latitude": 24.6517,
  "longitude": -81.435,
  "timezone": "America/New_York",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "8724266",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=8724266",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/8724266.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-fl-key-west",
    "height": {
      "type": "ratio",
      "high": 0.85,
      "low": 0.71
    },
    "time": {
      "high": -36,
      "low": 11
    }
  }
}

=== neaps/tide-database/data/us/ca/bishop-cut-disappointment-slough.json
{
  "id": "us-ca-bishop-cut-disappointment-slough",
  "name": "Bishop Cut, Disappointment Slough",
  "continent": "North America",
  "country": "United States",
  "region": "CA",
  "type": "subordinate",
  "latitude": 38.045,
  "longitude": -121.42,
  "timezone": "America/Los_Angeles",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "9415117",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=9415117",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/9415117.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-ca-port-chicago-suisun-bay",
    "height": {
      "type": "ratio",
      "high": 0.79,
      "low": 0.66
    },
    "time": {
      "high": 252,
      "low": 252
    }
  }
}

=== neaps/tide-database/data/us/ak/raven-bay.json
{
  "id": "us-ak-raven-bay",
  "name": "Raven Bay",
  "continent": "North America",
  "country": "United States",
  "region": "AK",
  "type": "subordinate",
  "latitude": 53.475,
  "longitude": -166.873,
  "timezone": "America/Nome",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "9462573",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=9462573",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/9462573.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-ak-unalaska",
    "height": {
      "type": "ratio",
      "high": 1.49,
      "low": 1.27
    },
    "time": {
      "high": -196,
      "low": -228
    }
  }
}
