=== neaps/tide-database/schemas/station.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://neaps.js.org/station.schema.json",
  "title": "Tide Station",
  "type": "object",
  "required": [
    "id",
    "name",
    "continent",
    "country",
    "type",
    "latitude",
    "longitude",
    "timezone",
    "source",
    "license"
  ],
  "additionalProperties": false,
  "$defs": {
    "offsets": {
      "type": "object",
      "description": "Offsets for subordinate stations relative to a reference station",
      "required": [
        "reference",
        "height",
        "time"
      ],
      "additionalProperties": false,
      "properties": {
        "reference": {
          "type": "string",
          "description": "The ID of the reference station"
        },
        "height": {
          "type": "object",
          "description": "Defines the values to add or multiply with water levels (depending on type)",
          "required": [
            "high",
            "low",
            "type"
          ],
          "additionalProperties": false,
          "properties": {
            "high": {
              "type": "number",
              "description": "Height offset/multiplier for high tide - if type is 'ratio', this is a multiplier; if 'fixed', this is an offset to add (can be negative)"
            },
            "low": {
              "type": "number",
              "description": "Height offset/multiplier for low tide - if type is 'ratio', this is a multiplier; if 'fixed', this is an offset to add (can be negative)"
            },
            "type": {
              "enum": [
                "ratio",
                "fixed"
              ]
            }
          }
        },
        "time": {
          "type": "object",
          "description": "Defines the time to add to when a high or low tide will occur",
          "required": [
            "high",
            "low"
          ],
          "additionalProperties": false,
          "properties": {
            "high": {
              "type": "number",
              "description": "Time offset, in minutes, to add to the high tide (can be negative)"
            },
            "low": {
              "type": "number",
              "description": "Time offset, in minutes, to add to the low tide (can be negative)"
            }
          }
        }
      }
    }
  },
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique station ID for this database only, in the format of `country-region-station-name`.",
      "examples": [
        "us-ma-boston",
        "ar-u-puerto-madryn"
      ],
      "minLength": 4
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "continent": {
      "type": "string",
      "description": "Continent name in title case (e.g., `North America`, `Asia`, `Europe`)",
      "minLength": 1
    },
    "country": {
      "type": "string",
      "description": "Full country name (e.g., `United States`)",
      "minLength": 1
    },
    "region": {
      "type": "string",
      "description": "ISO 3166-2 region code, if available. If not, whatever local postal codes"
    },
    "timezone": {
      "type": "string",
      "description": "IANA time zone code (e.g. `America/Los_Angeles`)"
    },
    "disclaimers": {
      "type": "string",
      "description": "Any disclaimers about using this data"
    },
    "type": {
      "type": "string",
      "enum": [
        "reference",
        "subordinate"
      ]
    },
    "latitude": {
      "type": "number",
      "description": "Latitude, in decimal degrees"
    },
    "longitude": {
      "type": "number",
      "description": "Longitude, in decimal degrees"
    },
    "source": {
      "type": "object",
      "description": "",
      "required": [
        "name",
        "id",
        "published_harmonics",
        "url",
        "source_url"
      ],
      "additionalProperties": true,
      "properties": {
        "name": {
          "type": "string",
          "name": "Name of the source, i.e. `NOAA`"
        },
        "id": {
          "type": [
            "string",
            "number"
          ],
          "description": "The identifier used by the source for this station."
        },
        "published_harmonics": {
          "type": "boolean",
          "description": "Are the harmonics from published harmonic data? False means harmonics were computed."
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "URL to this station's data or information in the source's website"
        },
        "source_url": {
          "type": "string",
          "format": "uri",
          "description": "URL to the source API endpoint for this station's data"
        }
      }
    },
    "license": {
      "type": "object",
      "description": "Defines the license and whatever restrictions are placed on use of the data.",
      "required": [
        "type",
        "commercial_use",
        "url"
      ],
      "additionalProperties": true,
      "properties": {
        "type": {
          "type": "string",
          "description": "A short description of the type of license (i.e. MIT, public domain, etc)"
        },
        "commercial_use": {
          "type": "boolean",
          "description": "If `true` then there are no restrictions on commercial use."
        },
        "url": {
          "type": "string",
          "format": "uri",
          "description": "A URL to the license information"
        },
        "notes": {
          "type": "string",
          "description": "Any additional restrictions or information on the license."
        }
      }
    },
    "harmonic_constituents": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "amplitude",
          "phase_UTC",
          "phase_local"
        ],
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string",
            "description": "Harmonic Constituent code (i.e. M2) - should be upper-case"
          },
          "description": {
            "type": [
              "string",
              "number",
              "null"
            ],
            "description": "Human-friendly description of the constituent"
          },
          "amplitude": {
            "type": "number",
            "description": "Amplitude"
          },
          "phase_UTC": {
            "type": "number",
            "description": "Phase in UTC"
          },
          "phase_local": {
            "type": "number",
            "description": "Phase for local timezone"
          },
          "speed": {
            "type": "number",
            "description": "Angular speed"
          },
          "comments": {
            "type": "string"
          }
        }
      }
    },
    "offsets": {
      "anyOf": [
        {
          "type": "object",
          "maxProperties": 0
        },
        {
          "$ref": "#/$defs/offsets"
        }
      ]
    },
    "datums": {
      "type": "object",
      "patternProperties": {
        "^[A-Z0-9_]+$": {
          "type": "number"
        }
      },
      "additionalProperties": false
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "type": {
            "const": "subordinate"
          }
        }
      },
      "then": {
        "properties": {
          "harmonic_constituents": {
            "maxItems": 0
          },
          "offsets": {
            "$ref": "#/$defs/offsets"
          }
        }
      }
    }
  ]
}

=== neaps/tide-database/data/us/wa/devils-head-drayton-passage.json
{
  "id": "us-wa-devils-head-drayton-passage",
  "name": "Devils Head, Drayton Passage",
  "continent": "North America",
  "country": "United States",
  "region": "WA",
  "type": "subordinate",
  "latitude": 47.1667,
  "longitude": -122.763,
  "timezone": "America/Los_Angeles",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "9446671",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=9446671",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/9446671.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-wa-seattle-madison-st-elliott-bay",
    "height": {
      "type": "ratio",
      "high": 1.25,
      "low": 1.1
    },
    "time": {
      "high": 40,
      "low": 50
    }
  }
}

=== neaps/tide-database/data/us/south-negril-point.json
{
  "id": "us-south-negril-point",
  "name": "South Negril Point",
  "continent": "North America",
  "country": "United States",
  "region": "",
  "type": "subordinate",
  "latitude": 18.3,
  "longitude": -78.4,
  "timezone": "America/Jamaica",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "TEC4701",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=TEC4701",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/TEC4701.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-tx-galveston-galveston-channel",
    "height": {
      "type": "ratio",
      "high": 1.21,
      "low": 1.21
    },
    "time": {
      "high": -167,
      "low": -167
    }
  }
}

=== neaps/tide-database/data/us/ak/el-capitan-passage-dry-pass.json
{
  "id": "us-ak-el-capitan-passage-dry-pass",
  "name": "El Capitan Passage, Dry Pass",
  "continent": "North America",
  "country": "United States",
  "region": "AK",
  "type": "reference",
  "latitude": 56.1633,
  "longitude": -133.413,
  "timezone": "America/Sitka",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "9450998",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=9450998",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/9450998.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "harmonic_constituents": [
    {
      "name": "M2",
      "description": "Principal lunar semidiurnal constituent",
      "amplitude": 1.352,
      "phase_UTC": 273,
      "phase_local": 12.1,
      "speed": 28.984104
    },
    {
      "name": "S2",
      "description": "Principal solar semidiurnal constituent",
      "amplitude": 0.463,
      "phase_UTC": 307,
      "phase_local": 37,
      "speed": 30
    },
    {
      "name": "N2",
      "description": "Larger lunar elliptic semidiurnal constituent",
      "amplitude": 0.29,
      "phase_UTC": 252.1,
      "phase_local": 356.1,
      "speed": 28.43973
    },
    {
      "name": "K1",
      "description": "Lunar diurnal constituent",
      "amplitude": 0.435,
      "phase_UTC": 261.3,
      "phase_local": 125.9,
      "speed": 15.041069
    },
    {
      "name": "M4",
      "description": "Shallow water overtides of principal lunar constituent",
      "amplitude": 0.007,
      "phase_UTC": 217.1,
      "phase_local": 55.4,
      "speed": 57.96821
    },
    {
      "name": "O1",
      "description": "Lunar diurnal constituent",
      "amplitude": 0.28,
      "phase_UTC": 248,
      "phase_local": 122.5,
      "speed": 13.943035
    },
    {
      "name": "M6",
      "description": "Shallow water overtides of principal lunar constituent",
      "amplitude": 0.01,
      "phase_UTC": 104.2,
      "phase_local": 41.7,
      "speed": 86.95232
    },
    {
      "name": "MK3",
      "description": "Shallow water terdiurnal",
      "amplitude": 0,
      "phase_UTC": 0,
      "phase_local": 0,
      "speed": 44.025173
    },
    {
      "name": "S4",
      "description": "Shallow water overtides of principal solar constituent",
      "amplitude": 0.001,
      "phase_UTC": 274.6,
      "phase_local": 94.6,
      "speed": 60
    },
    {
      "name": "MN4",
      "description": "Shallow water quarter diurnal constituent",
      "amplitude": 0,
      "phase_UTC": 0,
      "phase_local": 0,
      "speed": 57.423832
    },
    {
      "name": "NU2",
      "description": "Larger lunar evectional constituent",
      "amplitude": 0.056,
      "phase_UTC": 254.8,
      "phase_local": 358.2,
      "speed": 28.512583
    },
    {
      "name": "S6",
      "description": "Shallow water overtides of principal solar constituent",
      "amplitude": 0.001,
      "phase_UTC": 52.8,
      "phase_local": 322.8,
      "speed": 90
    },
    {
      "name": "MU2",
      "description": "Variational constituent",
      "amplitude": 0.032,
      "phase_UTC": 238.9,
      "phase_local": 347.2,
      "speed": 27.968208
    },
    {
      "name": "2N2",
      "description": "Lunar elliptical semidiurnal second-order constituent",
      "amplitude": 0.038,
      "phase_UTC": 231.2,
      "phase_local": 340.1,
      "speed": 27.895355
    },
    {
      "name": "OO1",
      "description": "Lunar diurnal",
      "amplitude": 0.012,
      "phase_UTC": 274.7,
      "phase_local": 129.4,
      "speed": 16.139101
    },
    {
      "name": "LAM2",
      "description": "Smaller lunar evectional constituent",
      "amplitude": 0.009,
      "phase_UTC": 288.8,
      "phase_local": 23.7,
      "speed": 29.455626
    },
    {
      "name": "S1",
      "description": "Solar diurnal constituent",
      "amplitude": 0,
      "phase_UTC": 0,
      "phase_local": 0,
      "speed": 15
    },
    {
      "name": "M1",
      "description": "Smaller lunar elliptic diurnal constituent",
      "amplitude": 0.02,
      "phase_UTC": 254.8,
      "phase_local": 124.3,
      "speed": 14.496694
    },
    {
      "name": "J1",
      "description": "Smaller lunar elliptic diurnal constituent",
      "amplitude": 0.022,
      "phase_UTC": 268,
      "phase_local": 127.7,
      "speed": 15.5854435
    },
    {
      "name": "MM",
      "description": "Lunar monthly constituent",
      "amplitude": 0,
      "phase_UTC": 0,
      "phase_local": 0,
      "speed": 0.5443747
    },
    {
      "name": "SSA",
      "description": "Solar semiannual constituent",
      "amplitude": 0.031,
      "phase_UTC": 161.1,
      "phase_local": 160.4,
      "speed": 0.0821373
    },
    {
      "name": "SA",
      "description": "Solar annual constituent",
      "amplitude": 0.115,
      "phase_UTC": 273.7,
      "phase_local": 273.3,
      "speed": 0.0410686
    },
    {
      "name": "MSF",
      "description": "Lunisolar synodic fortnightly constituent",
      "amplitude": 0,
      "phase_UTC": 0,
      "phase_local": 0,
      "speed": 1.0158958
    },
    {
      "name": "MF",
      "description": "Lunisolar fortnightly constituent",
      "amplitude": 0.027,
      "phase_UTC": 173,
      "phase_local": 163.1,
      "speed": 1.0980331
    },
    {
      "name": "RHO",
      "description": "Larger lunar evectional diurnal constituent",
      "amplitude": 0.011,
      "phase_UTC": 242.3,
      "phase_local": 121.1,
      "speed": 13.471515
    },
    {
      "name": "Q1",
      "description": "Larger lunar elliptic diurnal constituent",
      "amplitude": 0.054,
      "phase_UTC": 241.4,
      "phase_local": 120.8,
      "speed": 13.398661
    },
    {
      "name": "T2",
      "description": "Larger solar elliptic constituent",
      "amplitude": 0.027,
      "phase_UTC": 305.7,
      "phase_local": 36,
      "speed": 29.958933
    },
    {
      "name": "R2",
      "description": "Smaller solar elliptic constituent",
      "amplitude": 0.004,
      "phase_UTC": 308.4,
      "phase_local": 38,
      "speed": 30.041067
    },
    {
      "name": "2Q1",
      "description": "Larger elliptic diurnal",
      "amplitude": 0.007,
      "phase_UTC": 234.8,
      "phase_local": 119.1,
      "speed": 12.854286
    },
    {
      "name": "P1",
      "description": "Solar diurnal constituent",
      "amplitude": 0.144,
      "phase_UTC": 260.4,
      "phase_local": 125.7,
      "speed": 14.958931
    },
    {
      "name": "2SM2",
      "description": "Shallow water semidiurnal constituent",
      "amplitude": 0,
      "phase_UTC": 0,
      "phase_local": 0,
      "speed": 31.015896
    },
    {
      "name": "M3",
      "description": "Lunar terdiurnal constituent",
      "amplitude": 0,
      "phase_UTC": 0,
      "phase_local": 0,
      "speed": 43.47616
    },
    {
      "name": "L2",
      "description": "Smaller lunar elliptic semidiurnal constituent",
      "amplitude": 0.038,
      "phase_UTC": 293.9,
      "phase_local": 28.1,
      "speed": 29.528479
    },
    {
      "name": "2MK3",
      "description": "Shallow water terdiurnal constituent",
      "amplitude": 0,
      "phase_UTC": 0,
      "phase_local": 0,
      "speed": 42.92714
    },
    {
      "name": "K2",
      "description": "Lunisolar semidiurnal constituent",
      "amplitude": 0.126,
      "phase_UTC": 309.8,
      "phase_local": 39,
      "speed": 30.082138
    },
    {
      "name": "M8",
      "description": "Shallow water eighth diurnal constituent",
      "amplitude": 0.004,
      "phase_UTC": 223.8,
      "phase_local": 260.3,
      "speed": 115.93642
    },
    {
      "name": "MS4",
      "description": "Shallow water quarter diurnal constituent",
      "amplitude": 0,
      "phase_UTC": 0,
      "phase_local": 0,
      "speed": 58.984104
    }
  ],
  "datums": {
    "LAT": 0.19200015,
    "HAT": 5.953,
    "STND": 0,
    "MHHW": 4.885,
    "MHW": 4.634,
    "DTL": 3.095,
    "MTL": 3.182,
    "MSL": 3.177,
    "MLW": 1.73,
    "MLLW": 1.305,
    "GT": 3.58,
    "MN": 2.904,
    "DHQ": 0.251,
    "DLQ": 0.425,
    "HWI": 9.5,
    "LWI": 3.24
  },
  "disclaimers": ""
}

=== neaps/tide-database/data/us/md/deep-landing-swan-creek.json
{
  "id": "us-md-deep-landing-swan-creek",
  "name": "Deep Landing, Swan Creek",
  "continent": "North America",
  "country": "United States",
  "region": "MD",
  "type": "subordinate",
  "latitude": 39.145,
  "longitude": -76.26,
  "timezone": "America/New_York",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "8573211",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=8573211",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/8573211.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-md-baltimore-fort-mchenry",
    "height": {
      "type": "ratio",
      "high": 0.96,
      "low": 1.09
    },
    "time": {
      "high": 2,
      "low": -4
    }
  }
}

=== neaps/tide-database/data/us/hi/waimea-bay.json
{
  "id": "us-hi-waimea-bay",
  "name": "Waimea Bay",
  "continent": "North America",
  "country": "United States",
  "region": "HI",
  "type": "subordinate",
  "latitude": 21.9567,
  "longitude": -159.673,
  "timezone": "Pacific/Honolulu",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "1611401",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=1611401",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/1611401.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-hi-nawiliwili",
    "height": {
      "type": "ratio",
      "high": 0.86,
      "low": 0.91
    },
    "time": {
      "high": 7,
      "low": 18
    }
  }
}

=== neaps/tide-database/data/us/fl/o-hara-key-north-end-waltz-key-basin.json
{
  "id": "us-fl-o-hara-key-north-end-waltz-key-basin",
  "name": "O'Hara Key, north end, Waltz Key Basin",
  "continent": "North America",
  "country": "United States",
  "region": "FL",
  "type": "subordinate",
  "latitude": 24.6167,
  "longitude": -81.645,
  "timezone": "America/New_York",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "8724441",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=8724441",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/8724441.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-fl-key-west",
    "height": {
      "type": "ratio",
      "high": 1.03,
      "low": 0.83
    },
    "time": {
      "high": 233,
      "low": 339
    }
  }
}

=== neaps/tide-database/data/us/md/piney-point-md.json
{
  "id": "us-md-piney-point-md",
  "name": "Piney Point, Md.",
  "continent": "North America",
  "country": "United States",
  "region": "MD",
  "type": "subordinate",
  "latitude": 38.1333333,
  "longitude": -76.5333333,
  "timezone": "America/New_York",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "8578240",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=8578240",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/8578240.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-dc-washington-washington-channel-d-c",
    "height": {
      "type": "ratio",
      "high": 0.51,
      "low": 0.6
    },
    "time": {
      "high": -354,
      "low": -436
    }
  }
}

=== neaps/tide-database/data/us/nj/absecon-channel-state-route-87-bridge.json
{
  "id": "us-nj-absecon-channel-state-route-87-bridge",
  "name": "Absecon Channel, State Route 87 bridge",
  "continent": "North America",
  "country": "United States",
  "region": "NJ",
  "type": "subordinate",
  "latitude": 39.385,
  "longitude": -74.425,
  "timezone": "America/New_York",
  "source": {
    "name": "US National Oceanic and Atmospheric Administration",
    "id": "8534638",
    "published_harmonics": true,
    "url": "https://tidesandcurrents.noaa.gov/stationhome.html?id=8534638",
    "source_url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/8534638.json"
  },
  "license": {
    "type": "public domain",
    "commercial_use": true,
    "url": "https://tidesandcurrents.noaa.gov/disclaimers.html"
  },
  "offsets": {
    "reference": "us-nj-atlantic-city-ocean",
    "height": {
      "type": "ratio",
      "high": 0.96,
      "low": 1.13
    },
    "time": {
      "high": 38,
      "low": 26
    }
  }
}
